config/routes.rb
Rails.application.routes.draw do
  resources :audio_uploads
  devise_for :users
  root 'audio_uploads#index'

  get 'about' => 'pages#about' # creates about_path

  get 'contact' => 'pages#contact' # creates contact_path

end

app/models/audio_upload.rb
class AudioUpload < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	has_attached_file :audio 
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	validates_attachment_content_type :audio, :content_type => [ 'audio/mp3', 'audio/wav', 'audio/ogg']
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :password, :presence => true

  has_many :audio_uploads                   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/audio_uploads_controller.rb
class AudioUploadsController < ApplicationController
  before_action :set_audio_upload, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /audio_uploads
  def index
    @audio_uploads = AudioUpload.all.order("created_at DESC")
  end

  # GET /audio_uploads/1
  def show
  end

  # GET /audio_uploads/new
  def new
    @audio_upload = current_user.audio_uploads.build
  end

  # GET /audio_uploads/1/edit
  def edit
  end

  # POST /audio_uploads
  def create
    @audio_upload = current_user.audio_uploads.build(audio_upload_params)
      if @audio_upload.save
         redirect_to @audio_upload, notice: 'Audio upload was successfully created.'
      else
        render :new  
      end
  end

  # PATCH/PUT /audio_uploads/1
  def update
      if @audio_upload.update(audio_upload_params)
        redirect_to @audio_upload, notice: 'Audio upload was successfully updated.'
      else
        render :edit  
      end
  end

  # DELETE /audio_uploads/1
  def destroy
    @audio_upload.destroy
    redirect_to audio_uploads_url, notice: 'Audio upload was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio_upload
      @audio_upload = AudioUpload.find(params[:id])
    end

    def correct_user
      @audio_upload = current_user.audio_uploads.find_by(id: params[:id])
      redirect_to audio_uploads_path, notice: "Not authorized to edit this audio upload" if @audio_upload.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audio_upload_params
      params.require(:audio_upload).permit(:artist_name, :track_name, :image, :audio)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audio_uploads_helper.rb
module AudioUploadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/audio_uploads/_form.html.erb
<%= form_for @audio_upload, html: { multipart: true } do |f| %>
  <% if @audio_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audio_upload.errors.count, "error") %> prohibited this audio_upload from being saved:</h2>

      <ul>
      <% @audio_upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :audio %><br>
    <%= f.file_field :audio, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name, 'User Name' %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :artist_name, 'Artist Name' %><br>
    <%= f.text_field :artist_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :track_name, 'Track Name' %><br>
    <%= f.text_field :track_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/audio_uploads/edit.html.erb
<h1>Editing Audio Upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @audio_upload %> |
<%= link_to 'Back', audio_uploads_path %>

app/views/audio_uploads/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="audio_uploads" class="transitions-enabled">
  <% @audio_uploads.each do |audio_upload| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(audio_upload.image.url(:medium)), audio_upload %>
      <div class="panel-body">
      <p>
        <b><span style="color:red">User Name</span>: <% if audio_upload.user %><%= audio_upload.user.name %><% end %></b>
      </p>
      <p>
        <b><span style="color:red">Published</span>: <%= audio_upload.created_at %></b>
      </p>
      <p>
        <b><span style="color:red"><u>Artist</u></span>: <%= audio_upload.artist_name %></b>
      </p>
      <p>
        <b><span style="color:red"><u>Title</u></span >: <%= audio_upload.track_name %></b>
      </p>
      <p><strong><%= audio_upload.user.name if audio_upload.user %></strong></p>
      
      <% if current_user && audio_upload.user == current_user %>
   <div class="actions">
     <%= link_to edit_audio_upload_path(audio_upload) do %>
       <span class="glyphicon glyphicon-edit"></span>
       Edit
     <% end %>
     <%= link_to audio_upload, method: :delete, data: { confirm: 'Are you sure?' } do %>
       <span class="glyphicon glyphicon-trash"></span>
       Delete
     <% end %>
          </div>
        <% end %>
      
      </div>
    </div>
<% end %>
</div>



  

app/views/audio_uploads/new.html.erb
<h1>New Audio Upload</h1>

<%= render 'form' %>

<%= link_to 'Back', audio_uploads_path %>

app/views/audio_uploads/show.html.erb
<%= link_to  audio_uploads_path do %>
  <span class="glyphicon glyphicon-hand-left"></span>
  Back
<% end %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
				<p><%= image_tag @audio_upload.image.url(:medium) %></p>
				<p><b><span style="color:red">Published</span>: <%= @audio_upload.created_at %></b></p>
				<p><%= audio_tag @audio_upload.audio, :type => "audio/mp3", :controls => true, autoplay: true %></p>
			</div>

			<div class="panel-body">
				<p>
				  <strong><span style="color:red">Artist Name</span>:</strong>
				  <b><%= @audio_upload.artist_name %></b>
				</p>

				<p>
				  <strong><span style="color:red">Track Name</span>:</strong>
				  <b><%= @audio_upload.track_name %></b>
				</p>

				<% if @audio_upload.user == current_user %>
				  <%= link_to edit_audio_upload_path(@audio_upload) do%>
				    <span class="glyphicon glyphicon-edit"></span>
				      Edit |
				  <% end %> 
				<% end %>
			</div>
   </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "The Pengame", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      <li><%= link_to "Contact", contact_path %></li>
      <% if user_signed_in? %>
          <li>
            <%= link_to new_audio_upload_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Audio Upload
            <% end %>
          </li>
      <li><%= link_to "Account settings", edit_user_registration_path %></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %> 
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Pengame</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
<div class="container">
<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
<%= yield %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class=" jumbotron center">
<h1>Welcome to The Pengame</h1>

<p>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>
</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/pages/contact.html.erb</p>